# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd4707ca68a8001537373de754d60e37d4d7a00491496e655f312235da9ac3730ce80138d4a1f5798c84c7e8a4743c66e3ba6e379100be4b72b6ec419ff8ccf3

test:
  secret_key_base: b389902e9f3179dbc13cdc9f495d65b8b876d47ea061e2f08050bfe3fd505a804ec63f68f8a7c7374f4ecda9924a756b17076ae175fed874ecd8453157559ce1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
